name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: docker:19.03.10
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        npm install
        npm run-script build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build

        test:
          stage: test
          variables:
            DOCKER_DRIVER: overlay
            DOCKER_HOST: tcp://localhost:2375
            DOCKER_TLS_CERTDIR: ""
          script:
            - sh ./scripts/build_ci.sh
          timeout: 2 hours
          only:
            - develop
          tags:
            - qa


image: docker:19.03.10

stages:
  - test

services:
  - docker:dind

before_script:
  - docker info

